package tlc2.tool.impl.jit;

import net.bytebuddy.description.method.MethodDescription;
import net.bytebuddy.implementation.Implementation;
import net.bytebuddy.implementation.bytecode.StackManipulation;
import net.bytebuddy.implementation.bytecode.member.MethodInvocation;
import net.bytebuddy.jar.asm.Label;
import net.bytebuddy.jar.asm.MethodVisitor;
import net.bytebuddy.jar.asm.Opcodes;
import tlc2.value.impl.Enumerable;
import tlc2.value.impl.ValueEnumeration;

/**
 * Bytecode emitter for a compiled bounded-exists expression: {@code \E x \in S : P(x)}.
 * <p>
 * Contract for the parameters supplied at construction time:
 * <ul>
 *   <li>{@code domain} — a {@link StackManipulation} that, when applied, pushes the domain
 *       as a {@code Value} that is also an {@link Enumerable} on the JVM operand stack.</li>
 *   <li>{@code body} — a {@link StackManipulation} that reads the bound variable from
 *       local slot {@code xLocal} and pushes an {@code int} boolean (0/1) on the stack.
 *       It must already include any necessary kind-conversion to bool.</li>
 *   <li>{@code xLocal} — the JVM local variable slot allocated for the bound variable.</li>
 * </ul>
 * <p>
 * The generated bytecode is equivalent to:
 * <pre>{@code
 *   ValueEnumeration enum = ((Enumerable) domain).elements();
 *   Value elem;
 *   while ((elem = enum.nextElement()) != null) {
 *       xLocal = elem;
 *       if (body(xLocal)) return true;
 *   }
 *   return false;
 * }</pre>
 * Net stack effect: pushes one {@code int} (0 or 1).
 */
class BoundedExists implements StackManipulation {

    private static final MethodDescription ELEMENTS;
    private static final MethodDescription NEXT_ELEMENT;

    static {
        try {
            ELEMENTS = new MethodDescription.ForLoadedMethod(Enumerable.class.getMethod("elements"));
            NEXT_ELEMENT = new MethodDescription.ForLoadedMethod(ValueEnumeration.class.getMethod("nextElement"));
        } catch (NoSuchMethodException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    /** Pre-compiled domain expression – leaves a {@code Value} (Enumerable) on the stack. */
    private final StackManipulation domain;
    /**
     * Pre-compiled predicate body – the bound variable is already in {@code xLocal};
     * leaves a {@code bool:int} on the stack.
     */
    private final StackManipulation body;
    /** JVM local variable slot for the bound variable element. */
    private final int xLocal;

    BoundedExists(StackManipulation domain, StackManipulation body, int xLocal) {
        this.domain = domain;
        this.body = body;
        this.xLocal = xLocal;
    }

    @Override
    public boolean isValid() {
        return domain.isValid() && body.isValid();
    }

    /**
     * Emits the loop bytecode.
     *
     * <p>Stack layout per iteration step:
     * <pre>
     * ENTRY           [ ]
     * domain          [ enum_domain ]
     * CHECKCAST       [ enumerable  ]
     * elements()      [ enum        ]
     * LOOP_START:
     *   DUP           [ enum, enum  ]
     *   nextElement() [ enum, elem? ]
     *   DUP           [ enum, elem?, elem? ]
     *   IFNULL FOUND_NULL  → taken with [ enum, null ]
     *   ASTORE xLocal [ enum        ]
     *   body          [ enum, bool  ]
     *   IFNE FOUND_TRUE
     *   GOTO LOOP_START
     * FOUND_NULL:
     *   POP, POP      [ ]
     *   ICONST_0      [ 0 ]
     *   GOTO END
     * FOUND_TRUE:
     *   POP           [ ]
     *   ICONST_1      [ 1 ]
     * END:            [ bool:int ]
     * </pre>
     */
    @Override
    public Size apply(MethodVisitor mv, Implementation.Context ctx) {
        Label loopStart = new Label();
        Label foundNull = new Label();
        Label foundTrue = new Label();
        Label end       = new Label();

        // Push domain and obtain iterator.
        Size size = domain.apply(mv, ctx);                                          // [ domain ]
        mv.visitTypeInsn(Opcodes.CHECKCAST, "tlc2/value/impl/Enumerable");
        size = size.aggregate(MethodInvocation.invoke(ELEMENTS).apply(mv, ctx));    // [ enum ]

        mv.visitLabel(loopStart);
        mv.visitInsn(Opcodes.DUP);                                                  // [ enum, enum ]
        size = size.aggregate(MethodInvocation.invoke(NEXT_ELEMENT).apply(mv, ctx)); // [ enum, elem? ]
        mv.visitInsn(Opcodes.DUP);                                                  // [ enum, elem?, elem? ]
        mv.visitJumpInsn(Opcodes.IFNULL, foundNull);                                // [ enum, elem ]

        // Store element into bound variable local; evaluate predicate.
        mv.visitVarInsn(Opcodes.ASTORE, xLocal);                                    // [ enum ]
        size = size.aggregate(body.apply(mv, ctx));                                 // [ enum, bool:int ]
        mv.visitJumpInsn(Opcodes.IFNE, foundTrue);                                  // [ enum ]
        mv.visitJumpInsn(Opcodes.GOTO, loopStart);

        // Exhausted with no match: stack is [ enum, null ] → false.
        mv.visitLabel(foundNull);
        mv.visitInsn(Opcodes.POP);                                                  // [ enum ]
        mv.visitInsn(Opcodes.POP);                                                  // [ ]
        mv.visitInsn(Opcodes.ICONST_0);                                             // [ 0 ]
        mv.visitJumpInsn(Opcodes.GOTO, end);

        // Element found satisfying predicate: stack is [ enum ] → true.
        mv.visitLabel(foundTrue);
        mv.visitInsn(Opcodes.POP);                                                  // [ ]
        mv.visitInsn(Opcodes.ICONST_1);                                             // [ 1 ]

        mv.visitLabel(end);
        // Stack: [ bool:int ]

        // Net: +1 (one bool pushed). Max includes domain + body + loop overhead.
        return new Size(1, size.getMaximalSize() + 4);
    }
}
